### PR TITLE
Day/Week avg diff

### PR DESCRIPTION
**Pull request by 1rV1N-git**
ALTER TABLE pool.block_log ADD INDEX `diff` (`find_time`, `difficulty`);

### CODE REVIEW

**Comment by bobbieltd** [comment]
Do you mean we will add find_time and difficulty for hundreds of thousands of blocks just to use only 7 recent blocks’ info ? It will bloat the table. I prefer another light method.

**Comment by bobbieltd** [comment]
By the way, I like your idea about avgDiff for a day/a week.

**Comment by 1rV1N-git** [comment]
I add that code in my pool and load on mysql don't increase

**Comment by 1rV1N-git** [comment]
It isn't my idea. it is Venthos' idea
https://github.com/Venthos/nodejs-pool/commit/73a19d87482e90595624248aa593e91ee7e03d8d

**Comment by MoneroOcean** [comment]
Sorry. What is use case for that?

**Pull request closed without merging**
