### PR TITLE
fix bug

### PR DESCRIPTION
**Pull request by 1rV1N-git**

### CODE REVIEW

**Comment by bobbieltd** [comment]
@MoneroOcean By the way, your worker module makes a lot of unnecessary calls to coinmarketcap API price, it is better to get price outside of pool API request. If you agree with that, you do it or I make PR to make it better.

**Comment by MoneroOcean** [comment]
@bobbieltd it is working fine I think. CMC calls are on 20 second intervals or so which are pretty much OK.

**Comment by MoneroOcean** [comment]
I will apply change and fix it just after.

**Comment by bobbieltd** [comment]
It is weird. When I log price, everytime worker call CMC, it calls three times simultanously. I put CMC call to seperate function getCoinPrice and setInterval to it. Anyway, it is unimportant.

**Comment by bobbieltd** [comment]
Sorry, it is because of me using old codes (pplns, pps, solo update calls). You already fixed it in your repo.

**Pull request merged**
