### PR TITLE
Don't reduce maxDifficulty for proxy

### PR DESCRIPTION
**Pull request by 1rV1N-git**

### CODE REVIEW

**Comment by 1rV1N-git** [comment]
Forget to say. It is for miner with static diff. They get starting diff eq maxDiff.

**Comment by MoneroOcean** [comment]
It is kind of by design. Miners (proxy included) can not exceed global.config.pool.maxDifficulty. I think it is in their interest because if set too high their static diff can exceed coin diff otherwise and all will just loose money (some of their hashes will miss blocks).

**Comment by 1rV1N-git** [comment]
how about this 
https://github.com/MoneroOcean/nodejs-pool/blob/09cedca286f40e7665f3622ac1a08bf6c6ee0d46/lib/pool.js#L883

**Comment by MoneroOcean** [comment]
Good point. Will look history why this was added.

**Comment by MoneroOcean** [comment]
This added by Snipa: https://github.com/MoneroOcean/nodejs-pool/commit/687decc04d7c3433b5e529cc393a6e7b0aee3646

**Comment by MoneroOcean** [comment]
I think I will disable this special proxy diff handling.Will be safer this way.

**Comment by 1rV1N-git** [comment]
Ok.

**Pull request closed without merging**
